name: scoring
channels: 
  - conda-forge
  - defaults
dependencies:
  - ipython=7.12.0
  - matplotlib=3.1.3
  - nbconvert=5.6.1
  - numpy=1.18.1
  - python=3.8.1
  - scikit-learn=0.24.1
  - requests=2.25.1
  - matplotlib=3.1.3
  - scipy=1.5.3
  - pandas=1.2.3
  - pip=24.3.1
  - pip:
      - git+https://github.com/johntfoster/UTuning.git
